### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by suiboyu** [Kerinlin/localMusicPlayer#3]
```javascript
Uncaught TypeError: fs.existsSync is not a function
    at getElectronPath (index.js?bdb9:7)
    at Object.eval (index.js?bdb9:18)
    at eval (index.js:20)
    at Object../node_modules/electron/index.js (chunk-vendors.js:1390)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (App.vue?234e:12)
    at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (app.js:938)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
```
请问这个怎么解决，查了一些方法，都没有办法解决

**Comment by Kerinlin** [comment]
电脑是windows还是mac,node 版本号多少？

**Comment by Kerinlin** [comment]
> ```js
> Uncaught TypeError: fs.existsSync is not a function
>     at getElectronPath (index.js?bdb9:7)
>     at Object.eval (index.js?bdb9:18)
>     at eval (index.js:20)
>     at Object../node_modules/electron/index.js (chunk-vendors.js:1390)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
>     at eval (App.vue?234e:12)
>     at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (app.js:938)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
> ```
> 
> 请问这个怎么解决，查了一些方法，都没有办法解决

在app.vue中12行修改为
`const { ipcRenderer } = window.require("electron").remote;`

**Comment by Kerinlin** [comment]
> ```js
> Uncaught TypeError: fs.existsSync is not a function
>     at getElectronPath (index.js?bdb9:7)
>     at Object.eval (index.js?bdb9:18)
>     at eval (index.js:20)
>     at Object../node_modules/electron/index.js (chunk-vendors.js:1390)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
>     at eval (App.vue?234e:12)
>     at Module../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (app.js:938)
>     at __webpack_require__ (app.js:849)
>     at fn (app.js:151)
> ```
> 
> 请问这个怎么解决，查了一些方法，都没有办法解决

已更新，查看[代码更新](https://github.com/Kerinlin/localMusicPlayer/commit/d5c11054ed4648751540b5430568994751ef9f93)

**Comment by suiboyu** [comment]
> 电脑是windows还是mac,node 版本号多少？
window10，node版本 12.15.0

**Comment by Kerinlin** [comment]
> > 电脑是windows还是mac,node 版本号多少？
> > window10，node版本 12.15.0

看看是否解决？

**Comment by Kerinlin** [comment]
是在渲染进程引用了主进程的remote导致的错误,已经修复了，更换为通过ipc来告知主进程提供打开文件的路径
